FROM nginx:alpine

COPY index.html /usr/share/nginx/html

EXPOSE 1000

RUN chown -R 1067590018:root /etc/nginx
#RUN chown -R 1067590018:root /etc/conf.d
RUN chown -R 1067590018:root /var/cache/nginx
RUN chown -R 1067590018:root /var/run
RUN sed -i 's/nginx;/1067590018;/g' /etc/nginx/nginx.conf
RUN sed -i 's/80;/1000;/g' /etc/nginx/conf.d/default.conf

#To prevent nginx from self-demonizing and to run in foreground.
CMD ["nginx","-g","demon off;"]
